// Code generated by MockGen. DO NOT EDIT.
// Source: internal/clients/abstract/currency_client.go

// Package mock_abstract is a generated GoMock package.
package mock_abstract

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCurrencyExtractor is a mock of CurrencyExtractor interface.
type MockCurrencyExtractor struct {
	ctrl     *gomock.Controller
	recorder *MockCurrencyExtractorMockRecorder
}

// MockCurrencyExtractorMockRecorder is the mock recorder for MockCurrencyExtractor.
type MockCurrencyExtractorMockRecorder struct {
	mock *MockCurrencyExtractor
}

// NewMockCurrencyExtractor creates a new mock instance.
func NewMockCurrencyExtractor(ctrl *gomock.Controller) *MockCurrencyExtractor {
	mock := &MockCurrencyExtractor{ctrl: ctrl}
	mock.recorder = &MockCurrencyExtractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCurrencyExtractor) EXPECT() *MockCurrencyExtractorMockRecorder {
	return m.recorder
}

// GetHistoricalCurrency mocks base method.
func (m *MockCurrencyExtractor) GetHistoricalCurrency(day string) (map[string]float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistoricalCurrency", day)
	ret0, _ := ret[0].(map[string]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistoricalCurrency indicates an expected call of GetHistoricalCurrency.
func (mr *MockCurrencyExtractorMockRecorder) GetHistoricalCurrency(day interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistoricalCurrency", reflect.TypeOf((*MockCurrencyExtractor)(nil).GetHistoricalCurrency), day)
}

// GetLiveCurrency mocks base method.
func (m *MockCurrencyExtractor) GetLiveCurrency() (map[string]float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLiveCurrency")
	ret0, _ := ret[0].(map[string]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLiveCurrency indicates an expected call of GetLiveCurrency.
func (mr *MockCurrencyExtractorMockRecorder) GetLiveCurrency() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLiveCurrency", reflect.TypeOf((*MockCurrencyExtractor)(nil).GetLiveCurrency))
}
